/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TryRouteImport } from './routes/try'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as SignupSplatRouteImport } from './routes/signup.$'
import { Route as SigninSplatRouteImport } from './routes/signin.$'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AccountProfileRouteImport } from './routes/account.profile'

const TryRoute = TryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const SignupSplatRoute = SignupSplatRouteImport.update({
  id: '/signup/$',
  path: '/signup/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninSplatRoute = SigninSplatRouteImport.update({
  id: '/signin/$',
  path: '/signin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/recommendations': typeof RecommendationsRoute
  '/try': typeof TryRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/settings': typeof AccountSettingsRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/signin/$': typeof SigninSplatRoute
  '/signup/$': typeof SignupSplatRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/recommendations': typeof RecommendationsRoute
  '/try': typeof TryRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/settings': typeof AccountSettingsRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/signin/$': typeof SigninSplatRoute
  '/signup/$': typeof SignupSplatRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/recommendations': typeof RecommendationsRoute
  '/try': typeof TryRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/settings': typeof AccountSettingsRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/signin/$': typeof SigninSplatRoute
  '/signup/$': typeof SignupSplatRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/onboarding'
    | '/recommendations'
    | '/try'
    | '/account/profile'
    | '/account/security'
    | '/account/settings'
    | '/legal/$slug'
    | '/signin/$'
    | '/signup/$'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/recommendations'
    | '/try'
    | '/account/profile'
    | '/account/security'
    | '/account/settings'
    | '/legal/$slug'
    | '/signin/$'
    | '/signup/$'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/onboarding'
    | '/recommendations'
    | '/try'
    | '/account/profile'
    | '/account/security'
    | '/account/settings'
    | '/legal/$slug'
    | '/signin/$'
    | '/signup/$'
    | '/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  RecommendationsRoute: typeof RecommendationsRoute
  TryRoute: typeof TryRoute
  LegalSlugRoute: typeof LegalSlugRoute
  SigninSplatRoute: typeof SigninSplatRoute
  SignupSplatRoute: typeof SignupSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/signup/$': {
      id: '/signup/$'
      path: '/signup/$'
      fullPath: '/signup/$'
      preLoaderRoute: typeof SignupSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/$': {
      id: '/signin/$'
      path: '/signin/$'
      fullPath: '/signin/$'
      preLoaderRoute: typeof SigninSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountProfileRoute: AccountProfileRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  RecommendationsRoute: RecommendationsRoute,
  TryRoute: TryRoute,
  LegalSlugRoute: LegalSlugRoute,
  SigninSplatRoute: SigninSplatRoute,
  SignupSplatRoute: SignupSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
