/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/debug/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debug Recommendations */
        get: operations["debugRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/icons/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Icon Catalog */
        get: operations["getIconCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/baseline-taste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Baseline Taste */
        get: operations["getMyBaselineTaste"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch My Baseline Taste */
        patch: operations["patchMyBaselineTaste"];
        trace?: never;
    };
    "/me/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Ratings */
        get: operations["listMyRatings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Onboarding */
        post: operations["completeOnboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Rating */
        post: operations["createRating"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Recommendations */
        post: operations["postRecommendations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AbvIntent
         * @enum {string}
         */
        AbvIntent: "low" | "medium" | "high" | "any";
        /**
         * BaselineTasteDials
         * @description User-facing, editable taste dials derived from onboarding answers.
         */
        BaselineTasteDials: {
            /** Bitterness */
            bitterness: number;
            /** Bubbles */
            bubbles: number;
            /** Flavor Family */
            flavor_family: {
                [key: string]: number;
            };
            /** Novelty Affinity */
            novelty_affinity: number;
        };
        /**
         * BaselineTasteRecord
         * @description Persisted BaselineTaste returned by /me/baseline-taste.
         */
        BaselineTasteRecord: {
            /** Bitterness */
            bitterness: number;
            /** Bubbles */
            bubbles: number;
            /** Embedding Fresh At */
            embedding_fresh_at: string;
            /** Flavor Family */
            flavor_family: {
                [key: string]: number;
            };
            icons?: components["schemas"]["TasteProfileIcons"] | null;
            /** Novelty Affinity */
            novelty_affinity: number;
            /** Updated At */
            updated_at: string;
            /** User Id */
            user_id: string;
        };
        /**
         * Carbonation
         * @enum {string}
         */
        Carbonation: "still" | "light" | "strong";
        /** CatalogIconItem */
        CatalogIconItem: {
            /** Key */
            key: string;
            /** Purpose */
            purpose: string;
            /** Svg */
            svg: string;
        };
        /**
         * CitrusPick
         * @enum {string}
         */
        CitrusPick: "grapefruit" | "orange" | "lemonade" | "none";
        /**
         * CoffeeStyle
         * @enum {string}
         */
        CoffeeStyle: "black" | "espresso" | "hafuch" | "iced_sweet" | "none";
        /** ComponentStatus */
        ComponentStatus: {
            /** Detail */
            detail?: string | null;
            /**
             * Name
             * @enum {string}
             */
            name: "process" | "config" | "database" | "embedding_provider";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "down";
        };
        /** CreateRatingRequest */
        CreateRatingRequest: {
            /** Beer Id */
            beer_id: string;
            /** Note */
            note?: string | null;
            /** Rating */
            rating: number;
        };
        /**
         * DominantComponent
         * @enum {string}
         */
        DominantComponent: "baseline" | "session" | "abv" | "novelty_positive" | "novelty_negative";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** IconCatalogResponse */
        IconCatalogResponse: {
            /**
             * Flavors
             * @default []
             */
            flavors: components["schemas"]["CatalogIconItem"][];
            /**
             * Journey
             * @default []
             */
            journey: components["schemas"]["CatalogIconItem"][];
            /**
             * Marketing
             * @default []
             */
            marketing: components["schemas"]["CatalogIconItem"][];
            /**
             * Session Abv
             * @default []
             */
            session_abv: components["schemas"]["CatalogIconItem"][];
            /**
             * Session Vibes
             * @default []
             */
            session_vibes: components["schemas"]["CatalogIconItem"][];
        };
        /**
         * LovePref
         * @enum {string}
         */
        LovePref: "love" | "okay" | "avoid";
        /** OnboardingAnswers */
        OnboardingAnswers: {
            citrus: components["schemas"]["CitrusPick"];
            coffee: components["schemas"]["CoffeeStyle"];
            /** Novelty Seeking */
            novelty_seeking: boolean;
            smoked_foods: components["schemas"]["LovePref"];
            snack: components["schemas"]["SnackPick"];
            sour_foods: components["schemas"]["LovePref"];
            water: components["schemas"]["Carbonation"];
        };
        /** PatchBaselineTasteRequest */
        PatchBaselineTasteRequest: {
            /** Bitterness */
            bitterness?: number | null;
            /** Bubbles */
            bubbles?: number | null;
            /** Flavor Family */
            flavor_family?: {
                [key: string]: number;
            } | null;
            /** Novelty Affinity */
            novelty_affinity?: number | null;
        };
        /** RatingRecord */
        RatingRecord: {
            /** Beer Brewery */
            beer_brewery: string;
            /** Beer Id */
            beer_id: string;
            /** Beer Name */
            beer_name: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Note */
            note: string | null;
            /** Rating */
            rating: number;
        };
        /** RatingsHistoryResponse */
        RatingsHistoryResponse: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Ratings */
            ratings: components["schemas"]["RatingRecord"][];
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Components */
            components: components["schemas"]["ComponentStatus"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /**
         * RecommendationsRequest
         * @description Debug-style request: caller supplies the dials + intent directly.
         *
         *     Slice #76 introduces persisted BaselineTaste; this slice posts the
         *     answers inline to keep the smoke test independent of user persistence.
         */
        RecommendationsRequest: {
            /** Alpha */
            alpha?: number | null;
            baseline: components["schemas"]["BaselineTasteDials"];
            /** Beta */
            beta?: number | null;
            session?: components["schemas"]["SessionIntent"] | null;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** RecommendationsResponse */
        RecommendationsResponse: {
            /** Alpha */
            alpha: number;
            /** Beta */
            beta: number;
            /** Results */
            results: components["schemas"]["RecommendedBeer"][];
        };
        /** RecommendedBeer */
        RecommendedBeer: {
            /** Abv */
            abv: number;
            breakdown: components["schemas"]["ScoreBreakdown"];
            /** Brewery */
            brewery: string;
            /**
             * Color
             * @enum {string}
             */
            color: "pale" | "gold" | "amber" | "brown" | "dark";
            /** Id */
            id: string;
            /** Image Url */
            image_url?: string | null;
            /**
             * Market Tier
             * @enum {string}
             */
            market_tier: "mainstream" | "craft" | "import";
            /** Name */
            name: string;
            /** Style */
            style: string;
            /** Why Line */
            why_line: string;
        };
        /** ScoreBreakdown */
        ScoreBreakdown: {
            /** Abv Fits Intent */
            abv_fits_intent?: boolean | null;
            /** Abv Score */
            abv_score: number;
            /** Baseline Cos */
            baseline_cos: number;
            /** Baseline Score */
            baseline_score: number;
            dominant_component: components["schemas"]["DominantComponent"];
            /** Novelty Score */
            novelty_score: number;
            /** Session Cos */
            session_cos: number;
            /** Session Score */
            session_score: number;
            /** Total Score */
            total_score: number;
        };
        /** SessionIntent */
        SessionIntent: {
            abv_intent: components["schemas"]["AbvIntent"];
            /**
             * Free Text
             * @default
             */
            free_text: string;
            vibe: components["schemas"]["Vibe"];
        };
        /**
         * SnackPick
         * @enum {string}
         */
        SnackPick: "dark_chocolate" | "halva" | "fresh_fruit" | "milk_chocolate";
        /** TasteProfileIcon */
        TasteProfileIcon: {
            /** Flavor Key */
            flavor_key?: string | null;
            /** Purpose */
            purpose: string;
            /** Svg */
            svg: string;
        };
        /** TasteProfileIcons */
        TasteProfileIcons: {
            /** Flavors */
            flavors: components["schemas"]["TasteProfileIcon"][];
            hero: components["schemas"]["TasteProfileIcon"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Vibe
         * @enum {string}
         */
        Vibe: "refreshing" | "cozy" | "adventurous" | "familiar";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    debugRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    getIconCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IconCatalogResponse"];
                };
            };
        };
    };
    getMyBaselineTaste: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineTasteRecord"];
                };
            };
        };
    };
    patchMyBaselineTaste: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchBaselineTasteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineTasteRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listMyRatings: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingsHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    completeOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingAnswers"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineTasteRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createRating: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRatingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    postRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
