/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Challenge */
        post: operations["createChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/challenges/{token}/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare */
        post: operations["compareChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend */
        post: operations["recommendBeers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Qr */
        get: operations["resolveQrToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join */
        post: operations["joinSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommend */
        get: operations["getGroupRecommendation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["getSessionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit */
        post: operations["submitSessionVector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My History */
        get: operations["getMyHistory"];
        put?: never;
        /** Add To My History */
        post: operations["addToMyHistory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/persona": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Persona */
        get: operations["getMyPersona"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Profile */
        get: operations["getMyProfile"];
        /** Save My Profile */
        put: operations["saveMyProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rate Beer */
        post: operations["rateMyBeer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues/{venue_id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Venue Leaderboard */
        get: operations["getVenueLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues/{venue_id}/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan Venue Menu */
        post: operations["scanVenueMenu"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues/{venue_id}/tap-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tap List */
        get: operations["getTapList"];
        /** Set Tap List */
        put: operations["setTapList"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddHistoryRequest */
        AddHistoryRequest: {
            /** Beer Id */
            beer_id: string;
            rating?: components["schemas"]["RatingValue"] | null;
        };
        /** BeerPayload */
        BeerPayload: {
            /** Brewery */
            brewery?: string | null;
            /** Description */
            description?: string | null;
            /** Flavor Vector */
            flavor_vector: number[];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Style */
            style: string;
        };
        /** ChallengeComparisonResponse */
        ChallengeComparisonResponse: {
            challenger_persona: components["schemas"]["PersonaSummary"];
            /** Different */
            different: string[];
            friend_persona: components["schemas"]["PersonaSummary"];
            /** Shared */
            shared: string[];
            /** Similarity */
            similarity: number;
        };
        /** ChallengeTokenResponse */
        ChallengeTokenResponse: {
            /** Token */
            token: string;
        };
        /** ChallengeVectorRequest */
        ChallengeVectorRequest: {
            /** Vector */
            vector: number[];
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** Host Id */
            host_id: string;
        };
        /** CreateSessionResponse */
        CreateSessionResponse: {
            /** Expires At */
            expires_at: string;
            /** Session Id */
            session_id: string;
        };
        /** FlavorVector */
        FlavorVector: {
            /** Adventure */
            adventure: number;
            /** Bitterness */
            bitterness: number;
            /** Body */
            body: number;
            /** Fruitiness */
            fruitiness: number;
            /** Roast */
            roast: number;
            /** Sourness */
            sourness: number;
            /** Sweetness */
            sweetness: number;
        };
        /** GroupRecommendationResponse */
        GroupRecommendationResponse: {
            /** Group Vector */
            group_vector: number[];
            /** High Variance */
            high_variance: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** HistoryEntry */
        HistoryEntry: {
            /** Beer Id */
            beer_id: string;
            rating: components["schemas"]["RatingValue"] | null;
            /** Tried At */
            tried_at: string;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Entries */
            entries: components["schemas"]["HistoryEntry"][];
        };
        /** JoinSessionRequest */
        JoinSessionRequest: {
            /** Name */
            name: string;
        };
        /** JoinSessionResponse */
        JoinSessionResponse: {
            /** Participant Id */
            participant_id: string;
        };
        /** LeaderboardEntryResponse */
        LeaderboardEntryResponse: {
            /** Persona Icon */
            persona_icon: string;
            /** Rank */
            rank: number;
            /** Recommendation Count */
            recommendation_count: number;
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
        };
        /** LeaderboardResponse */
        LeaderboardResponse: {
            /** Entries */
            entries: components["schemas"]["LeaderboardEntryResponse"][];
            /** Viewer Rank */
            viewer_rank: number | null;
        };
        /** OkResponse */
        OkResponse: {
            /** Ok */
            ok: boolean;
        };
        /** PersonaResponse */
        PersonaResponse: {
            persona: components["schemas"]["PersonaSummary"] | null;
        };
        /** PersonaSummary */
        PersonaSummary: {
            /** Description */
            description?: string | null;
            /** Icon */
            icon: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** User Id */
            user_id: string;
            /** Vector */
            vector: number[] | null;
        };
        /** RateBeerRequest */
        RateBeerRequest: {
            beer: components["schemas"]["RatedBeerInput"];
            rating: components["schemas"]["RatingValue"];
        };
        /** RatedBeerInput */
        RatedBeerInput: {
            /** Brewery */
            brewery?: string | null;
            /** Description */
            description?: string | null;
            /** Flavor Vector */
            flavor_vector: number[];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Style */
            style: string;
        };
        /**
         * RatingValue
         * @enum {string}
         */
        RatingValue: "loved" | "fine" | "disliked";
        /** RecommendationRequest */
        RecommendationRequest: {
            /** Beers */
            beers: components["schemas"]["BeerPayload"][];
            taste_vector: components["schemas"]["FlavorVector"];
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            adventurous: components["schemas"]["BeerPayload"] | null;
            backup: components["schemas"]["BeerPayload"] | null;
            best: components["schemas"]["BeerPayload"];
            /** Explanations */
            explanations: {
                [key: string]: string;
            };
        };
        /** SaveProfileRequest */
        SaveProfileRequest: {
            /** Vector */
            vector: number[];
        };
        /** ScanCatalogEntry */
        ScanCatalogEntry: {
            /** Brewery */
            brewery: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ScanMenuRequest */
        ScanMenuRequest: {
            /** Catalog */
            catalog: components["schemas"]["ScanCatalogEntry"][];
            /** Image Base64 */
            image_base64: string;
        };
        /** ScanResultItem */
        ScanResultItem: {
            /** Confidence */
            confidence: number;
            /** Matched Id */
            matched_id: string | null;
            /** Needs Review */
            needs_review: boolean;
            /** Raw Text */
            raw_text: string;
        };
        /** SessionParticipantStatus */
        SessionParticipantStatus: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Submitted */
            submitted: boolean;
        };
        /** SessionStatusResponse */
        SessionStatusResponse: {
            /** Completed */
            completed: number;
            /** Participants */
            participants: components["schemas"]["SessionParticipantStatus"][];
            /** Session Id */
            session_id: string;
            /** Total */
            total: number;
        };
        /** SubmitVectorRequest */
        SubmitVectorRequest: {
            /** Participant Id */
            participant_id: string;
            /** Vector */
            vector: number[];
        };
        /** TapListRequest */
        TapListRequest: {
            /** Beer Ids */
            beer_ids: string[];
        };
        /** TapListResponse */
        TapListResponse: {
            /** Beer Ids */
            beer_ids: string[];
            /** Venue Id */
            venue_id: string;
        };
        /** UpdatedVectorResponse */
        UpdatedVectorResponse: {
            /** Updated Vector */
            updated_vector: number[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeTokenResponse"];
                };
            };
        };
    };
    compareChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeVectorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    recommendBeers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolveQrToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TapListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    joinSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getGroupRecommendation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupRecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSessionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submitSessionVector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitVectorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getMyHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
        };
    };
    addToMyHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddHistoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getMyPersona: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaResponse"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    saveMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rateMyBeer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateBeerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatedVectorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getVenueLeaderboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scanVenueMenu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanMenuRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResultItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getTapList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TapListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setTapList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TapListRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TapListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
