/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/debug/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debug Recommendations */
        get: operations["debugRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guest-recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Guest Recommendations */
        post: operations["postGuestRecommendations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/icons/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Icon Catalog */
        get: operations["getIconCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete My Account */
        delete: operations["deleteMyAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/baseline-taste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Baseline Taste */
        get: operations["getMyBaselineTaste"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export My Account */
        get: operations["exportMyAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Ratings */
        get: operations["listMyRatings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Onboarding */
        post: operations["completeOnboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rate/deck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rate Deck */
        get: operations["getRateDeck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rate/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Rate Session */
        post: operations["postRateSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Rating */
        post: operations["createRating"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Recommendations */
        post: operations["postRecommendations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AbvIntent
         * @enum {string}
         */
        AbvIntent: "low" | "medium" | "high" | "any";
        /**
         * AccountDeletionResponse
         * @description Contract the web client uses to then complete Clerk sign-out.
         */
        AccountDeletionResponse: {
            /** Deleted */
            deleted: boolean;
        };
        /**
         * AccountExport
         * @description Portable copy of a user's Beerolog-owned data (no internal embedding).
         */
        AccountExport: {
            baseline_taste: components["schemas"]["ExportBaselineTaste"] | null;
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string | null;
            /** Id */
            id: string;
            /** Ratings */
            ratings: components["schemas"]["ExportRating"][];
        };
        /**
         * AdventureLevel
         * @enum {string}
         */
        AdventureLevel: "low" | "medium" | "high";
        /**
         * AvoidCue
         * @enum {string}
         */
        AvoidCue: "too_bitter" | "too_sweet" | "too_heavy" | "too_dark";
        /**
         * BaselineTasteDials
         * @description User-facing, editable taste dials derived from onboarding answers.
         */
        BaselineTasteDials: {
            /**
             * Abv Affinity
             * @default 0.5
             */
            abv_affinity: number;
            /** Bitterness */
            bitterness: number;
            /**
             * Body
             * @default 0.5
             */
            body: number;
            /** Bubbles */
            bubbles: number;
            /** Flavor Family */
            flavor_family: {
                [key: string]: number;
            };
            /** Novelty Affinity */
            novelty_affinity: number;
            /**
             * Sweetness
             * @default 0.5
             */
            sweetness: number;
        };
        /**
         * BaselineTasteRecord
         * @description Persisted BaselineTaste returned by /me/baseline-taste.
         */
        BaselineTasteRecord: {
            /** Abv Affinity */
            abv_affinity: number;
            /** Bitterness */
            bitterness: number;
            /** Body */
            body: number;
            /** Bubbles */
            bubbles: number;
            /** Embedding Fresh At */
            embedding_fresh_at: string;
            /** Flavor Family */
            flavor_family: {
                [key: string]: number;
            };
            icons?: components["schemas"]["TasteProfileIcons"] | null;
            /** Model Version */
            model_version: number;
            /** Novelty Affinity */
            novelty_affinity: number;
            persona?: components["schemas"]["TasteProfilePersona"] | null;
            /** Sweetness */
            sweetness: number;
            /** Updated At */
            updated_at: string;
            /** User Id */
            user_id: string;
        };
        /**
         * Carbonation
         * @enum {string}
         */
        Carbonation: "still" | "light" | "strong";
        /** CatalogIconItem */
        CatalogIconItem: {
            /** Key */
            key: string;
            /** Purpose */
            purpose: string;
            /** Svg */
            svg: string;
        };
        /**
         * ChocoPref
         * @enum {string}
         */
        ChocoPref: "dark_90" | "dark_70" | "milk" | "none";
        /**
         * CoffeeStyle
         * @enum {string}
         */
        CoffeeStyle: "black" | "milk_based" | "sweet" | "none";
        /** ComponentStatus */
        ComponentStatus: {
            /** Detail */
            detail?: string | null;
            /**
             * Name
             * @enum {string}
             */
            name: "process" | "config" | "database" | "embedding_provider";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "down";
        };
        /** CreateRatingRequest */
        CreateRatingRequest: {
            /** Beer Id */
            beer_id: string;
            /** Note */
            note?: string | null;
            /**
             * Rating
             * @enum {string}
             */
            rating: "loved" | "fine" | "disliked";
        };
        /** DeckBeer */
        DeckBeer: {
            /** Abv */
            abv: number;
            /** Brewery */
            brewery: string;
            /** Color */
            color?: string | null;
            /** Id */
            id: string;
            /** Image Url */
            image_url?: string | null;
            /**
             * Market Tier
             * @enum {string}
             */
            market_tier: "mainstream" | "craft" | "import";
            /** Name */
            name: string;
            /** Name Hebrew */
            name_hebrew?: string | null;
            /** Style */
            style: string;
        };
        /**
         * DominantComponent
         * @enum {string}
         */
        DominantComponent: "baseline" | "session" | "abv" | "novelty_positive" | "novelty_negative";
        /** ExportBaselineTaste */
        ExportBaselineTaste: {
            /** Bitterness */
            bitterness: number;
            /** Bubbles */
            bubbles: number;
            /** Flavor Family */
            flavor_family: {
                [key: string]: number;
            };
            /** Novelty Affinity */
            novelty_affinity: number;
        };
        /** ExportRating */
        ExportRating: {
            /** Beer Id */
            beer_id: string;
            /** Note */
            note: string | null;
            /** Rating */
            rating: string | null;
        };
        /**
         * FlavorCue
         * @enum {string}
         */
        FlavorCue: "grapefruit" | "caramel" | "pine" | "tropical" | "banana_bread" | "citrus_zest" | "coffee" | "bread_crust";
        /** GuestRecommendationsResponse */
        GuestRecommendationsResponse: {
            /** Results */
            results: components["schemas"]["GuestRecommendedBeer"][];
            /** Unlocked Count */
            unlocked_count: number;
        };
        /**
         * GuestRecommendedBeer
         * @description Slimmed result for the public guest preview.
         *
         *     Deliberately decoupled from the authed RecommendedBeer: no score
         *     breakdown, a plain integer match_percent, and a plain `why` string.
         */
        GuestRecommendedBeer: {
            /** Abv */
            abv: number;
            /** Brewery */
            brewery: string;
            /**
             * Color
             * @enum {string}
             */
            color: "pale" | "gold" | "amber" | "brown" | "dark";
            /** Id */
            id: string;
            /** Image Url */
            image_url?: string | null;
            /** Match Percent */
            match_percent: number;
            /** Name */
            name: string;
            /** Name Hebrew */
            name_hebrew?: string | null;
            /** Style */
            style: string;
            /** Why */
            why: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** IconCatalogResponse */
        IconCatalogResponse: {
            /**
             * Flavors
             * @default []
             */
            flavors: components["schemas"]["CatalogIconItem"][];
            /**
             * Journey
             * @default []
             */
            journey: components["schemas"]["CatalogIconItem"][];
            /**
             * Marketing
             * @default []
             */
            marketing: components["schemas"]["CatalogIconItem"][];
            /**
             * Session Abv
             * @default []
             */
            session_abv: components["schemas"]["CatalogIconItem"][];
            /**
             * Session Vibes
             * @default []
             */
            session_vibes: components["schemas"]["CatalogIconItem"][];
        };
        /**
         * LovePref
         * @enum {string}
         */
        LovePref: "love" | "okay" | "avoid";
        /**
         * MatchCalibration
         * @description Fixed affine anchors for user-facing cosine % (not result-set normalization).
         */
        MatchCalibration: {
            /** Cos Ceiling */
            cos_ceiling: number;
            /** Cos Floor */
            cos_floor: number;
        };
        /** OnboardingAnswers */
        OnboardingAnswers: {
            adventure: components["schemas"]["AdventureLevel"];
            /** Avoids */
            avoids?: components["schemas"]["AvoidCue"][];
            chocolate?: components["schemas"]["ChocoPref"] | null;
            coffee: components["schemas"]["CoffeeStyle"];
            /** Flavor Cues */
            flavor_cues?: components["schemas"]["FlavorCue"][];
            smoked_foods: components["schemas"]["LovePref"];
            sour_foods: components["schemas"]["LovePref"];
            sour_wild?: components["schemas"]["SourWild"] | null;
            strength: components["schemas"]["StrengthPref"];
            sweet_tooth: components["schemas"]["SweetPref"];
            water: components["schemas"]["Carbonation"];
        };
        /** RateDeckResponse */
        RateDeckResponse: {
            /** Beers */
            beers: components["schemas"]["DeckBeer"][];
        };
        /** RateSessionRequest */
        RateSessionRequest: {
            /** Swipes */
            swipes: components["schemas"]["RateSwipe"][];
        };
        /** RateSessionResponse */
        RateSessionResponse: {
            /** Recorded */
            recorded: number;
        };
        /** RateSwipe */
        RateSwipe: {
            /** Beer Id */
            beer_id: string;
            /** Note */
            note?: string | null;
            /**
             * Rating
             * @enum {string}
             */
            rating: "loved" | "fine" | "disliked";
        };
        /** RatingRecord */
        RatingRecord: {
            /** Beer Brewery */
            beer_brewery: string;
            /** Beer Id */
            beer_id: string;
            /** Beer Name */
            beer_name: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Note */
            note: string | null;
            /**
             * Rating
             * @enum {string}
             */
            rating: "loved" | "fine" | "disliked";
        };
        /** RatingsHistoryResponse */
        RatingsHistoryResponse: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Ratings */
            ratings: components["schemas"]["RatingRecord"][];
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Components */
            components: components["schemas"]["ComponentStatus"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /**
         * RecommendationsRequest
         * @description Debug-style request: caller supplies the dials + intent directly.
         *
         *     Slice #76 introduces persisted BaselineTaste; this slice posts the
         *     answers inline to keep the smoke test independent of user persistence.
         */
        RecommendationsRequest: {
            /** Alpha */
            alpha?: number | null;
            baseline: components["schemas"]["BaselineTasteDials"];
            /** Beta */
            beta?: number | null;
            session?: components["schemas"]["SessionIntent"] | null;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** RecommendationsResponse */
        RecommendationsResponse: {
            /** Alpha */
            alpha: number;
            /** Beta */
            beta: number;
            calibration: components["schemas"]["MatchCalibration"];
            /** Results */
            results: components["schemas"]["RecommendedBeer"][];
        };
        /** RecommendedBeer */
        RecommendedBeer: {
            /** Abv */
            abv: number;
            breakdown: components["schemas"]["ScoreBreakdown"];
            /** Brewery */
            brewery: string;
            /**
             * Color
             * @enum {string}
             */
            color: "pale" | "gold" | "amber" | "brown" | "dark";
            /** Id */
            id: string;
            /** Image Url */
            image_url?: string | null;
            /**
             * Market Tier
             * @enum {string}
             */
            market_tier: "mainstream" | "craft" | "import";
            /** Name */
            name: string;
            /** Name Hebrew */
            name_hebrew?: string | null;
            /** Style */
            style: string;
            why: components["schemas"]["WhyLine"];
        };
        /** ScoreBreakdown */
        ScoreBreakdown: {
            /** Abv Fits Intent */
            abv_fits_intent?: boolean | null;
            /** Abv Score */
            abv_score: number;
            /** Baseline Cos */
            baseline_cos: number;
            /** Baseline Score */
            baseline_score: number;
            dominant_component: components["schemas"]["DominantComponent"];
            /** Novelty Score */
            novelty_score: number;
            /** Session Cos */
            session_cos: number;
            /** Session Score */
            session_score: number;
            /** Total Score */
            total_score: number;
        };
        /** SessionIntent */
        SessionIntent: {
            abv_intent: components["schemas"]["AbvIntent"];
            /**
             * Free Text
             * @default
             */
            free_text: string;
            vibe: components["schemas"]["Vibe"];
        };
        /**
         * SourWild
         * @enum {string}
         */
        SourWild: "bright" | "funky";
        /**
         * StrengthPref
         * @enum {string}
         */
        StrengthPref: "light" | "medium" | "strong";
        /**
         * SweetPref
         * @enum {string}
         */
        SweetPref: "rich" | "balanced" | "dry";
        /** TasteProfileIcon */
        TasteProfileIcon: {
            /** Flavor Key */
            flavor_key?: string | null;
            /** Purpose */
            purpose: string;
            /** Svg */
            svg: string;
        };
        /** TasteProfileIcons */
        TasteProfileIcons: {
            /** Flavors */
            flavors: components["schemas"]["TasteProfileIcon"][];
            hero: components["schemas"]["TasteProfileIcon"];
        };
        /**
         * TasteProfilePersona
         * @description LLM-generated, cosmetic taste persona, persisted per language.
         */
        TasteProfilePersona: {
            /** Blurb En */
            blurb_en: string;
            /** Blurb He */
            blurb_he: string;
            /** Title En */
            title_en: string;
            /** Title He */
            title_he: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Vibe
         * @enum {string}
         */
        Vibe: "refreshing" | "cozy" | "adventurous" | "familiar";
        /**
         * WhyLine
         * @description Language-neutral recommendation explanation.
         *
         *     The API picks the code + params; the frontend renders the localized
         *     sentence (key why.<code>). Keeps copy in one place and the embedding
         *     templates English-only.
         */
        WhyLine: {
            /** Code */
            code: string;
            /** Params */
            params?: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    debugRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsResponse"];
                };
            };
        };
    };
    postGuestRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingAnswers"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestRecommendationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    getIconCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IconCatalogResponse"];
                };
            };
        };
    };
    deleteMyAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDeletionResponse"];
                };
            };
        };
    };
    getMyBaselineTaste: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineTasteRecord"];
                };
            };
        };
    };
    exportMyAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountExport"];
                };
            };
        };
    };
    listMyRatings: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingsHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    completeOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingAnswers"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineTasteRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRateDeck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateDeckResponse"];
                };
            };
        };
    };
    postRateSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createRating: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRatingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    postRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
